# Generated by Django 4.1.6 on 2023-02-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fructs", "0003_localuser_product_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="isDemo",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
