# Generated by Django 4.1 on 2022-08-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fructs", "0004_product_sante"),
    ]

    operations = [
        migrations.CreateModel(
            name="Breadcumb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("subtitle", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(name="product", options={"ordering": ("name",)},),
    ]
