# Generated by Django 4.1.6 on 2023-02-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fructs", "0004_product_isdemo"),
    ]
    
    operations = [
         migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50)),
                ("link", models.CharField(blank=True, max_length=50, null=True)),
                ("note", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Featured",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("paragraph", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
