# Generated by Django 4.1.6 on 2023-02-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fructs", "0005_featured"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adresse", models.CharField(max_length=50)),
                ("street", models.CharField(blank=True, max_length=50, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("town", models.CharField(blank=True, max_length=50, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="title",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
