# Generated by Django 4.1.6 on 2023-02-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fructs", "0007_subscribedusers_subscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="tester_images"),
                ),
                ("name", models.CharField(max_length=50)),
                ("work", models.CharField(max_length=20)),
                ("declaration", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50)),
            ],
        ),
    ]
