# Generated by Django 4.1.6 on 2023-02-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fructs", "0007_location_email_location_innner_location_outter"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
