# Generated by Django 4.1.6 on 2023-02-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fructs", "0008_testimonial_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="title",
            name="link",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
