# Generated by Django 4.1.6 on 2023-02-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fructs", "0008_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
