# Generated by Django 4.1 on 2022-08-29 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fructs', '0002_categorie_unitie'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fructs.categorie'),
        ),
        migrations.AddField(
            model_name='product',
            name='unite',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='fructs.unitie'),
        ),
    ]
