# Generated by Django 4.1.1 on 2022-09-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fructs", "0006_mail"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscribedUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("conf_num", models.CharField(max_length=15)),
                ("confirmed", models.BooleanField(default=False)),
            ],
        ),
    ]
